version: '3.6'
services:

  nginx:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
      target: nginx-build
    volumes:
      - ./conf/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./data/nginx/log/:/var/log/nginx/
    ports:
    - "${ANGULAR_DJANGO_HTTP_PORT:-80:80}"
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.angular-django.rule=Host(`${ANGULAR_DJANGO_DOMAIN}`)"
      - "traefik.http.routers.angular-django.entrypoints=websecure"
      - "traefik.http.routers.angular-django.tls.certresolver=certbot"

  angular:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: angular-build

  gunicorn:
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    build:
      context: .
      dockerfile: ./Dockerfile
      target: gunicorn-build
    environment:
      DATA_DIRECTORY: /data
    volumes:
      - ./data/gunicorn/:/data/

