# Generated by Django 2.0.6 on 2018-06-13 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GrowthRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20)),
                ('formula', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50)),
                ('height', models.PositiveSmallIntegerField()),
                ('weight', models.PositiveSmallIntegerField()),
                ('base_experience', models.PositiveSmallIntegerField()),
                ('order', models.PositiveSmallIntegerField()),
                ('is_default', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('1', 'black'), ('2', 'blue'), ('3', 'brown'), ('4', 'gray'), ('5', 'green'), ('6', 'pink'), ('7', 'purple'), ('8', 'red'), ('9', 'white'), ('10', 'yellow')], max_length=8)),
                ('gender_rate', models.SmallIntegerField()),
                ('capture_rate', models.PositiveSmallIntegerField()),
                ('base_happiness', models.PositiveSmallIntegerField()),
                ('is_baby', models.BooleanField()),
                ('hatch_counter', models.PositiveSmallIntegerField()),
                ('has_gender_differences', models.BooleanField()),
                ('forms_switchable', models.BooleanField()),
                ('order', models.PositiveSmallIntegerField()),
                ('conquest_order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('evolves_from_specie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.Specie')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pokedex.Generation')),
                ('growth_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pokedex.GrowthRate')),
                ('habitat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pokedex.Habitat')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pokedex.Shape')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.Specie'),
        ),
        migrations.AddField(
            model_name='generation',
            name='main_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pokedex.Region'),
        ),
    ]
